# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EAE7E5
background         #1F1F21
cursor             #A0A3AC

active_tab_foreground     #1F1F21
active_tab_background     #EAE7E5
inactive_tab_foreground   #EAE7E5
inactive_tab_background   #1F1F21

active_border_color   #EAE7E5
inactive_border_color #1F1F21
bell_border_color     #404756

color0      #464648
color1		#404756
color2		#404756
color3		#404756
color4		#414856
color5		#828080
color6		#928B88
color7		#D8D4D1
color8		#979493
color9		#565F72
color10		#565F72
color11		#565F72
color12		#565F72
color13		#AEAAAB
color14		#C2B9B5
color15		#D8D4D1
