# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F4F4F7
background         #1F1F23
cursor             #9295A2

active_tab_foreground     #1F1F23
active_tab_background     #F4F4F7
inactive_tab_foreground   #F4F4F7
inactive_tab_background   #1F1F23

active_border_color   #F4F4F7
inactive_border_color #1F1F23
bell_border_color     #24283A

color0      #454649
color1		#24283A
color2		#24293A
color3		#404657
color4		#666B7C
color5		#666B7C
color6		#A7A8AD
color7		#E7E7EB
color8		#A1A2A4
color9		#30364D
color10		#30364D
color11		#565D74
color12		#888FA6
color13		#888FA6
color14		#DFE0E7
color15		#E7E7EB
