# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #ECE5F0
background         #202024
cursor             #9C96B1

active_tab_foreground     #202024
active_tab_background     #ECE5F0
inactive_tab_foreground   #ECE5F0
inactive_tab_background   #202024

active_border_color   #ECE5F0
inactive_border_color #202024
bell_border_color     #161727

color0      #46464B
color1		#161727
color2		#393556
color3		#6D649E
color4		#6D649E
color5		#976364
color6		#98889F
color7		#DCD2E1
color8		#9A939E
color9		#1D1E34
color10		#4C4673
color11		#9186D2
color12		#9186D2
color13		#C98486
color14		#CAB5D4
color15		#DCD2E1
