# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1F1F23)
$foreground = rgb(F4F4F7)
$color0 = rgb(454649)
$color1 = rgb(24283A)
$color2 = rgb(24293A)
$color3 = rgb(404657)
$color4 = rgb(666B7C)
$color5 = rgb(666B7C)
$color6 = rgb(A7A8AD)
$color7 = rgb(E7E7EB)
$color8 = rgb(A1A2A4)
$color9 = rgb(30364D)
$color10 = rgb(30364D)
$color11 = rgb(565D74)
$color12 = rgb(888FA6)
$color13 = rgb(888FA6)
$color14 = rgb(DFE0E7)
$color15 = rgb(E7E7EB)
