exec-once = $HOME/.config/hypr/initial-boot.sh

### Sourcing external config files ###
$configs = $HOME/.config/hypr/configs # Default Configs directory path
$UserConfigs = $HOME/.config/hypr/configs # Configs directory path
$scriptsDir = $HOME/.config/hypr/scripts # Scripts directory path
$UserScripts = $HOME/.config/hypr/UserScripts # User Scripts directory path
$mainMod = SUPER # Main modifier key

source=$configs/keybinds.conf # Pre-configured keybinds

# Load defaults, then user additions/overrides
source= $configs/startup_apps.conf

source= $configs/en_variables.conf # Environment variables (defaults)

# For laptop related
source= $configs/laptops.conf
source= $UserConfigs/laptops.conf

# Load defaults, then user additions
source= $configs/window_rules.conf # Window Rules and Layer Rules

source= $configs/system_settings.conf # Default config for hypr

source= $UserConfigs/decorations.conf # Decorations config file
source= $UserConfigs/animations.conf # Animation config file
source= $UserConfigs/01_defaults.conf # settings for User defaults apps

# nwg-displays
source= $HOME/.config/hypr/configs/monitors.conf
source= $HOME/.config/hypr/workspaces.conf
