Diagnostics:
    UnusedIncludes: Strict
    MissingIncludes: Strict

Completion:
    AllScopes: Yes
    ArgumentLists: FullPlaceholders

InlayHints:
    Enabled: true
    BlockEnd: false
    Designators: true
    ParameterNames: true
    DeducedTypes: true
    DefaultArguments: true

Hover:
    ShowAKA: true

